In [7]:
import pandas as pd

person = pd.DataFrame({
    "id": [1, 2, 3],
    "email": ["a@b.com", "c@d.com", "a@b.com"]
})

person

   id    email
0   1  a@b.com
1   2  c@d.com
2   3  a@b.com

In [21]:
find = person.duplicated(subset="email",keep=False)

duplicated_email =person[find].iloc[[0]]
duplicated_email

   id    email
0   1  a@b.com

In [23]:
import pandas as pd

customers = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "name": ["Joe", "Henry", "Sam", "Max"]
})

orders = pd.DataFrame({
    "id": [1, 2],
    "customerId": [3, 1]
})

print(customers)
print(orders)

   id   name
0   1    Joe
1   2  Henry
2   3    Sam
3   4    Max
   id  customerId
0   1           3
1   2           1

In [46]:
merged = pd.merge(customers,orders,left_on="id",right_on="customerId",how="inner")
result= merged[["id_x","name"]].rename(columns={
    "id_x":"id",
})
find = customers[["name"]].isin([result["name"]])
find

    name
0  False
1  False
2  False
3  False